import pandas as pd

class Data_Reader: 
    """
    Lazily reads DEL dataset files and holds metadata about columns.
    Supports CSV (chunked) and Parquet. Use named constructors to instantiate.
    """

    class Fields(Enum):
        DATA = "data"
        BUILDING_BLOCKS = "building_blocks"
        MOLECULE_SMILES = "molecule_smiles"


    def __init__(self):
        # Placeholder attributes; they will be set by classmethods
        #original column names when the object is instantiated, used for renaming and formatting
        self.building_blocks = None
        self.molecule_smiles=None
        self.misc_cols = None
        #metadata counting how many building block columns were specified
        self.n_building_blocks = None
        #dictionary to convert from original column names to canonical names, generated by the classmethods

        #original source file path
        self.source_file = None

        self.chunk_size = None
        self.n_chunks = None
        self.actual_chunk_sizes=None

from enum import Enum
import pandas as pd

class Data_Reader:
    """Class to hold data and related attributes"""

    class Fields(Enum):
        DATA = "data"
        BUILDING_BLOCKS = "building_blocks"
        MOLECULE_SMILES = "molecule_smiles"

    def __init__(self):
        self.data = None
        self.building_blocks = None
        self.molecule_smiles = None


    # ------------------------------------------------------------------ #
    #  Construction                                                        #
    # ------------------------------------------------------------------ #

    @classmethod
    def from_csv(cls, filepath: str,
                        building_blocks: list ,
                        chunk_size: int = None,
                        molecule_smiles: str = None ,
                        id_col: str = None,
                        misc_cols: list = None,
                        **kwargs):
        """
        Reads a CSV file in chunks, formats columns, and returns an iterator of DataFrames
        with canonical column names and order.
        """

        if chunk_size is not None and (chunk_size <= 0 or not isinstance(chunk_size, int)):
            raise ValueError("chunk_size must be positive & non zero integer.")
        

        self = cls()
        self.building_blocks = building_blocks
        self.molecule_smiles=molecule_smiles
        self.misc_cols = misc_cols
        self.n_building_blocks = len(building_blocks)
        self.source_file = filepath
        self.chunk_size = chunk_size
        self.n_chunks=self._compute_n_chunks()
        self.actual_chunk_sizes=self._get_actual_chunk_sizes()
        return self


    @classmethod
    def from_parquet(cls, filepath: str, **kwargs): #!TO BE DONE
        """
        Reads a Parquet file. Chunking is not supported. #pyarrow.dataset does support it maybe we should make that be the enginge for parquet.

        Returns:
            pd.DataFrame: The loaded DataFrame.
        """
        cls.df = pd.read_parquet(filepath, **kwargs)
        return cls.df

    # ------------------------------------------------------------------ #
    #  Data access                                                         #
    # ------------------------------------------------------------------ #

    @property
    def data(self):
        """Always returns a fresh iterable of DataFrames."""
        if self.chunk_size is None:
            return [pd.read_csv(self.source_file)]  # wrap in list
        else:
            return pd.read_csv(self.source_file, chunksize=self.chunk_size)


    def get_chunk(self, n:int):
        data=self.data
        if n < 0:
            raise ValueError("Chunk index must be >= 0")
        try:
            for i, chunk in enumerate(data):
                    if i == n:
                        self.chunk = chunk
                        return chunk
        except Exception as e:
            self.chunk = None 
            print(f"Data loaded does not have {n} chunks.")
            return None


    # ------------------------------------------------------------------ #
    #  Validation                                                          #
    # ------------------------------------------------------------------ #


    def validate_required_data(self, required_fields):
        """
        Validates that this Data_Reader instance has all required attributes
        defined and not None (or empty).
        """
        missing = []

        for field in required_fields:
            # if Enum, get its value; otherwise assume string
            field_name = field.value if hasattr(field, "value") else field
            try:
                value = getattr(self, field_name)
            except AttributeError:
                missing.append(f"{field_name} (not defined)")
                continue

            if value is None:
                missing.append(field_name)
            elif hasattr(value, "empty") and value.empty:
                missing.append(f"{field_name} (empty)")
            elif isinstance(value, (list, dict, set)) and len(value) == 0:
                missing.append(f"{field_name} (empty)")

        if missing:
            raise ValueError(
                f"Missing required data for {type(self).__name__}: {', '.join(missing)}"
            )


    # ------------------------------------------------------------------ #
    #  Private helpers                                                     #
    # ------------------------------------------------------------------ #


    def _compute_n_chunks(self): #!might be slow
        if self.chunk_size is None:
            return 1
        else:
            # count rows without loading full file
            row_count = sum(1 for _ in open(self.source_file)) - 1  
            return -(-row_count // self.chunk_size)   
    

    def _get_actual_chunk_sizes(self):
        if self.chunk_size is None:
            return [sum(1 for _ in open(self.source_file)) - 1]
        
        row_count = sum(1 for _ in open(self.source_file)) - 1
        n_chunks = -(-row_count // self.chunk_size)
        
        sizes = [self.chunk_size] * (n_chunks - 1)
        last_size = row_count - self.chunk_size * (n_chunks - 1)
        sizes.append(last_size)
        return sizes






